name: Labeled

on:
  issues:
    types: [labeled]

jobs:
  labeled:
    if: ${{ github.event.label.name == 'bug' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.issue.assignees }}
