name: Labeled

on:
  issues:
    types: [labeled]

jobs:
  labeled:
    if: ${{ github.event.label.name == 'bug' && toJSON(github.event.issue.assignees) == '[]' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'bug issue without assignees'
